name: ci
on:
  push:
  pull_request:
  schedule:
    - cron: "0 6 * * 1"  # weekly Monday 06:00 UTC

jobs:
  test-and-audit:
    runs-on: ubuntu-latest
    env:
      # App config for tests (not secrets in prod)
      APP_ENV: dev
      STRICT_SECRETS: "true"
      SECRET_KEY: "this_is_a_demo_only_super_long_secret_key_at_least_64_chars_1234567890"
      ACCESS_MINUTES: "30"
      BODY_MAX_BYTES: "1048576"
      RATE_LIMIT_LOGIN_MAX: "5"
      RATE_LIMIT_LOGIN_WINDOW: "60"
      FRONTEND_ORIGINS: "http://127.0.0.1:5173,http://localhost:5173"
      DATABASE_URL: "sqlite:///./dev.db"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install fastapi uvicorn pydantic "python-jose[cryptography]" "passlib[argon2]" structlog python-dotenv sqlalchemy httpx pytest pip-audit bandit
          fi

      - name: Run tests
        run: pytest -q

      - name: pip-audit (CVE scan)
        run: pip-audit -r requirements.txt --strict 

      - name: Bandit (static checks)
        run: bandit -q -r app
